# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
        aws.storage:
            adapter: 'sftp'
            options:
                host: '%env(resolve:SFTP_HOST_AWS)%'
                port: 22
                username: '%env(resolve:SFTP_USERNAME_AWS)%'
                password: ''
                privateKey: '%env(resolve:SFTP_KEY_AWS)%'
                root: '/sftpamazonkpgroup'
                timeout: 60
                directoryPerm: 0744
                permPublic: 0700
                permPrivate: 0744
        kpssport.storage:        
            adapter: 'ftp'
            options:
                host: '%env(resolve:EXPORT_JSON_HOST)%'
                username: '%env(resolve:EXPORT_JSON_USERNAME)%'
                password: '%env(resolve:EXPORT_JSON_PASSWORD)%'
                port: 21
                root: '%env(resolve:EXPORT_JSON_DIRECTORY)%'
                passive: true
                timeout: 30
                ignore_passive_address: ~
                utf8: false                
