# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
        aws.storage:
            adapter: 'sftp'
            options:
                host: '%env(resolve:SFTP_HOST_AWS)%'
                port: 22
                username: '%env(resolve:SFTP_USERNAME_AWS)%'
                password: ''
                privateKey: '%env(resolve:SFTP_KEY_AWS)%'
                root: '/sftpamazonkpgroup'
                timeout: 60
                directoryPerm: 0744
                permPublic: 0700
                permPrivate: 0744
        kpssport.storage:        
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/report'
        product.storage:        
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/products'
        ariseLabel.storage:        
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/labels' 
        dhl.storage:
            adapter: 'sftp'
            options:
                host: '%env(resolve:DHL_HOST)%'
                port: 22
                username: '%env(resolve:DHL_USERNAME)%'
                password: '%env(resolve:DHL_PASSWORD)%'
                privateKey: 
                root: '/out'
                timeout: 60
                directoryPerm: 0744
                permPublic: 0700
                permPrivate: 0744             
        channelAdvisor.storage:
            adapter: 'sftp'
            options:
                host: '%env(resolve:CHANNEL_SFTP_HOST)%'
                port: 22
                username: '%env(resolve:CHANNEL_SFTP_USERNAME)%'
                password: '%env(resolve:CHANNEL_SFTP_PASSWORD)%'
                privateKey: 
                root: '/'
                timeout: 60
                directoryPerm: 0744
                permPublic: 0700
                permPrivate: 0744 