# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _instanceof:
        App\Service\Aggregator\StockParent:
            tags: ['app.stockupdater']
        App\Service\Aggregator\UpdateStatusParent:
            tags: ['app.statusupdater']
        App\Service\Aggregator\ApiInterface:
            tags: ['app.apiconnector']
        App\Service\Aggregator\IntegratorParent:
            tags: ['app.integrator']
        App\BusinessCentral\Connector\BusinessCentralConnector:
            tags: ['app.businesscentralconnector']
        App\Service\Aggregator\PriceParent:
            tags: ['app.priceupdater']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Aggregator\IntegratorAggregator:
        arguments:
            - !tagged_iterator app.integrator
    App\Service\Aggregator\ApiAggregator:
        arguments:
            - !tagged_iterator app.apiconnector
    App\Service\Aggregator\UpdateStatusAggregator:
        arguments:
            - !tagged_iterator app.statusupdater
    App\Service\Aggregator\StockAggregator:
        arguments:
            - !tagged_iterator app.stockupdater
    App\Service\Aggregator\PriceAggregator:
        arguments:
            - !tagged_iterator app.priceupdater
    App\BusinessCentral\Connector\BusinessCentralAggregator:
        arguments:
            - !tagged_iterator app.businesscentralconnector
            
    

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $channelEndpoint : '%env(resolve:CHANNEL_ENDPOINT)%'
            $channelRefreshToken : '%env(resolve:CHANNEL_REFRESHTOKEN)%'
            $channelApplicationId : '%env(resolve:CHANNEL_APPLICATIONID)%'
            $channelSharedSecret : '%env(resolve:CHANNEL_SECRET)%'
            
            $urlBC : '%env(resolve:BC_URL)%'
            $loginBC : '%env(resolve:BC_LOGIN)%'
            $passwordBC : '%env(resolve:BC_PASSWORD)%'

            $appEnv : '%env(resolve:APP_ENV)%'

            $amzLwaId : '%env(resolve:AMZ_LWA_ID)%'
            $amzLwaSecret  : '%env(resolve:AMZ_LWA_SECRET)%'
            $amzAwsId  : '%env(resolve:AMZ_AWS_ID)%'
            $amzAwsSecret  : '%env(resolve:AMZ_AWS_SECRET)%'
            $amzArn  : '%env(resolve:AMZ_ARN)%'
            $amzRefreshToken  : '%env(resolve:AMZ_REFRESH_TOKEN)%'

            $akeneoUrl  : '%env(resolve:AKENEO_URL)%'
            $akeneoClientId  : '%env(resolve:AKENEO_CLIENT_ID)%'
            $akeneoClientSecret  : '%env(resolve:AKENEO_CLIENT_SECRET)%'
            $akeneoUsername  : '%env(resolve:AKENEO_USERNAME)%'
            $akeneoPassword  : '%env(resolve:AKENEO_PASSWORD)%'

            $aliExpressClientId :  '%env(resolve:ALI_EXPRESS_ID)%'
            $aliExpressClientSecret : '%env(resolve:ALI_EXPRESS_SECRET)%'
            $aliExpressClientAccessToken : '%env(resolve:ALI_EXPRESS_TOKEN)%'

            $ariseClientId :  '%env(resolve:ARISE_ID)%'
            $ariseClientSecret : '%env(resolve:ARISE_SECRET)%'
            $ariseClientRefreshToken : '%env(resolve:ARISE_REFRESH_TOKEN)%'

            $amazfitClientId :  '%env(resolve:AMAZFIT_ARISE_ID)%'
            $amazfitClientSecret : '%env(resolve:AMAZFIT_ARISE_SECRET)%'
            $amazfitClientRefreshToken : '%env(resolve:AMAZFIT_ARISE_REFRESH_TOKEN)%'

            $fitbitExpressClientId :  '%env(resolve:FITBIT_EXPRESS_ID)%'
            $fitbitExpressClientSecret : '%env(resolve:FITBIT_EXPRESS_SECRET)%'
            $fitbitExpressClientAccessToken : '%env(resolve:FITBIT_EXPRESS_TOKEN)%'

            $owletCareToken : '%env(resolve:OWLET_CARE_TOKEN)%'
            $owletCareClientId : '%env(resolve:OWLET_CARE_CLIENTID)%'
            $owletCareClientSecret : '%env(resolve:OWLET_CARE_CLIENTSECRET)%'
            $owletCareShopDomain : '%env(resolve:OWLET_CARE_SHOPDOMAINE)%'
            $owletCareVersion : '%env(resolve:OWLET_CARE_VERSION)%'
            $owletCareScopes : '%env(resolve:OWLET_CARE_SCOPES)%'

            $minibattToken : '%env(resolve:MINIBATT_TOKEN)%'
            $minibattClientId : '%env(resolve:MINIBATT_CLIENTID)%'
            $minibattClientSecret : '%env(resolve:MINIBATT_CLIENTSECRET)%'
            $minibattShopDomain : '%env(resolve:MINIBATT_SHOPDOMAINE)%'
            $minibattVersion : '%env(resolve:MINIBATT_VERSION)%'
            $minibattScopes : '%env(resolve:MINIBATT_SCOPES)%'

            $flashledToken : '%env(resolve:FLASHLED_TOKEN)%'
            $flashledClientId : '%env(resolve:FLASHLED_CLIENTID)%'
            $flashledClientSecret : '%env(resolve:FLASHLED_CLIENTSECRET)%'
            $flashledShopDomain : '%env(resolve:FLASHLED_SHOPDOMAINE)%'
            $flashledVersion : '%env(resolve:FLASHLED_VERSION)%'
            $flashledScopes : '%env(resolve:FLASHLED_SCOPES)%'

            $fitbitCorporateToken : '%env(resolve:FITBITCORPORATE_TOKEN)%'
            $fitbitCorporateClientId : '%env(resolve:FITBITCORPORATE_CLIENTID)%'
            $fitbitCorporateClientSecret : '%env(resolve:FITBITCORPORATE_CLIENTSECRET)%'
            $fitbitCorporateShopDomain : '%env(resolve:FITBITCORPORATE_SHOPDOMAINE)%'
            $fitbitCorporateVersion : '%env(resolve:FITBITCORPORATE_VERSION)%'
            $fitbitCorporateScopes : '%env(resolve:FITBITCORPORATE_SCOPES)%'

          
            
